version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: pos_postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: posdb
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pos_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: dwfitksa@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8080:80"

volumes:
  postgres_data:
